http:
  middlewares:
    basic-auth:
      basicAuth:
        users:
          # Generated via: htpasswd -nbB admin 'STRONG_PASSWORD'
          - "admin:$2y$05$7ObYZdiXe7IzQR.ZJF0VzeN/uxmvQAPTabmwvYQQfX2TQCGqmMv06"

    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer-when-downgrade"
        permissionsPolicy: "camera=(), microphone=()"

    noindex:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow, noarchive"
